GTR <- read.delim("../../GTR_table.txt", header = T, stringsAsFactors = F)
GTR_10x <- read.delim("../../coverage_tables/GTR_10x.txt", header = T, stringsAsFactors = F)
GTR_20x <- read.delim("../../coverage_tables/GTR_20x.txt", header = T, stringsAsFactors = F)
GTR_30x <- read.delim("../../coverage_tables/GTR_30x.txt", header = T, stringsAsFactors = F)

gene_symbol <- readRDS("data/gene_symbol.rds")
gnomad_exome <- readRDS("data/gnomad_exome.rds")
colnames(GTR)
summary <- readRDS("../data/summary.rds")
x <- as.data.frame(table(summary$gene), stringsAsFactors = F)
y <- as.data.frame(table(GTR$GeneSymbol), stringsAsFactors = F)
y <- subset(y, Var1 %in% x$Var1)
x <- x[order(x[1,])]
y <- y[order(y[1,])]
head(x)
load10x(summary)
load20x(summary)
load30x(summary)


nums <- unlist(lapply(SAS_30x,is.numeric))
SAS_30x <- SAS_30x[,nums]

AFR_mean_10x <- rowMeans(AFR_10x)
AFR_mean_20x <- rowMeans(AFR_20x)
AFR_mean_30x <- rowMeans(AFR_30x)
AMR_mean_10x <- rowMeans(AMR_10x)
AMR_mean_20x <- rowMeans(AMR_20x)
AMR_mean_30x <- rowMeans(AMR_30x)
EAS_mean_10x <- rowMeans(EAS_10x)
EAS_mean_20x <- rowMeans(EAS_20x)
EAS_mean_30x <- rowMeans(EAS_30x)
EUR_mean_10x <- rowMeans(EUR_10x)
EUR_mean_20x <- rowMeans(EUR_20x)
EUR_mean_30x <- rowMeans(EUR_30x)
SAS_mean_10x <- rowMeans(SAS_10x)
SAS_mean_20x <- rowMeans(SAS_20x)
SAS_mean_30x <- rowMeans(SAS_30x)

AFR_min_10x <- apply(AFR_10x, 1, FUN=min)
AFR_min_20x <- apply(AFR_20x, 1, FUN=min)
AFR_min_30x <- apply(AFR_30x, 1, FUN=min)
AMR_min_10x <- apply(AMR_10x, 1, FUN=min)
AMR_min_20x <- apply(AMR_20x, 1, FUN=min)
AMR_min_30x <- apply(AMR_30x, 1, FUN=min)
EAS_min_10x <- apply(EAS_10x, 1, FUN=min)
EAS_min_20x <- apply(EAS_20x, 1, FUN=min)
EAS_min_30x <- apply(EAS_30x, 1, FUN=min)
EUR_min_10x <- apply(EUR_10x, 1, FUN=min)
EUR_min_20x <- apply(EUR_20x, 1, FUN=min)
EUR_min_30x <- apply(EUR_30x, 1, FUN=min)
SAS_min_10x <- apply(SAS_10x, 1, FUN=min)
SAS_min_20x <- apply(SAS_20x, 1, FUN=min)
SAS_min_30x <- apply(SAS_30x, 1, FUN=min)

AFR_max_10x <- apply(AFR_10x, 1, FUN=max)
AFR_max_20x <- apply(AFR_20x, 1, FUN=max)
AFR_max_30x <- apply(AFR_30x, 1, FUN=max)
AMR_max_10x <- apply(AMR_10x, 1, FUN=max)
AMR_max_20x <- apply(AMR_20x, 1, FUN=max)
AMR_max_30x <- apply(AMR_30x, 1, FUN=max)
EAS_max_10x <- apply(EAS_10x, 1, FUN=max)
EAS_max_20x <- apply(EAS_20x, 1, FUN=max)
EAS_max_30x <- apply(EAS_30x, 1, FUN=max)
EUR_max_10x <- apply(EUR_10x, 1, FUN=max)
EUR_max_20x <- apply(EUR_20x, 1, FUN=max)
EUR_max_30x <- apply(EUR_30x, 1, FUN=max)
SAS_max_10x <- apply(SAS_10x, 1, FUN=max)
SAS_max_20x <- apply(SAS_20x, 1, FUN=max)
SAS_max_30x <- apply(SAS_30x, 1, FUN=max)

# master <- data.frame(summary$ccds_id, summary$gene, x$Freq, y$Freq)

colnames(summary)
gene_symbol <- unique(summary$gene)
ccds_ids <- c()
global_mean <- c()
GTR_tests <- c()

for (i in 1:length(gene_symbol)) {
  ccds_ids[i] <- paste(subset(summary, gene == gene_symbol[i])$ccds_id, collapse = " ")
  global_mean[i] <- mean(subset(summary, gene == gene_symbol[i])$GTR_average_10x)
  GTR_tests[i] <- paste(subset(GTR, GeneSymbol == gene_symbol[i])$AccessionVersion, collapse = " ")
}

table <- data.frame(gene_symbol, ccds_ids, global_mean, GTR_tests)
